### ISSUE TITLE
Error: no such option: -h

### ISSUE THREAD

**Issue by jshuping** [Oxygem/canaryd#12]
It would be nice for canaryctl/canaryd to allow the -h option instead of typing --help.
Same with others like -d for --debug.  Thanks!

**Comment by Fizzadar** [comment]
Thanks for the suggestion, @jshuping! I've now added this in https://github.com/Oxygem/canaryd/commit/8500dc5597ca0b2ab2952d2d49b5876663341bec. We're aiming to release `0.3` in a couple of weeks, with a dev version in the next few days.
