### ISSUE TITLE
Incorrect IP reported in UI

### ISSUE THREAD

**Issue by jshuping** [Oxygem/canaryd#15]
I have machines that reach the Internet via a NAT gateway.
In the Web UI, I see the same IP for all the machines.
I am not sure if it was intended to report the IP of the local network interface(s).

**Comment by Fizzadar** [comment]
@jshuping this is intended - the IP listed on the site is meant to match the public IP that Service Canary sees as data comes in for that server.

Sidenote: I am looking into adding network interfaces and traffic rates (and % utilised) to the monitor plugin.
